arch = "AArch64"
name = "CoRF+ctrl-isb"
hash = "5ee7f8b1485e9f39f749667c019ed42e"
symbolic = []

[[self_modify]]
address = "f:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[thread.0]
init = { X1 = "f:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
"""

[thread.1]
init = { X2 = "f:" }
code = """
	LDR W0,[X2]
	CBNZ W0,l
l:
	ISB
	BL f
	MOV W1,W10
	B Lout
f:
	B l0
l1:
	MOV W10,#2
	RET
l0:
	MOV W10,#1
	RET
Lout:
"""

[final]
expect = "sat"
assertion = "1:X0 = 0x14000001 & 1:X1 = 1"
