arch = "AArch64"
name = "MP.RF+dc-dmb+ctrl-isb"
hash = "aa12f4764cc18b135573b6978dde960f"
symbolic = ["x"]

[[self_modify]]
address = "L4:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[locations]
"x" = "0"

[types]
"x" = "int64_t"

[thread.0]
init = { X3 = "x", X1 = "L4:", X0 = "0x14000001" }
code = """
	STR W0,[X1]
	DC CVAU,X1
	DMB SY
	MOV X2,#1
	STR X2,[X3]
"""

[thread.1]
init = { X2 = "x" }
code = """
	MOV X9,#0
L3:
	LDR X1,[X2]
	CBZ X1,L3
	ISB
L4:
	B Lfail
	B Lout
Lfail:
	MOV X9,#1
Lout:
"""

[final]
expect = "sat"
assertion = "1:X9 = 1"
