arch = "AArch64"
name = "MP.RF+dmb+addr-cachesync"
hash = "97cc989391e0647317842c77c9edf2c6"
symbolic = ["x", "z"]

[[self_modify]]
address = "f:"
bytes = 4
values = [
  "0x14000001",
  "0x14000003"
]

[locations]
"x" = "0"
"z" = "0"

[types]
"x" = "uint64_t"
"z" = "uint64_t"

[thread.0]
init = { X3 = "x", X1 = "f:", X0 = "0x14000001", X2 = "1" }
code = """
	STR W0,[X1]
	DMB SY
	STR X2,[X3]
"""

[thread.1]
init = { X6 = "f:", X5 = "z", X2 = "x", X0 = "0" }
code = """
	LDR X0,[X2]
	EOR X3,X0,X0
	LDR X4,[X5,X3]
	DC CVAU,X6
	DSB ISH
	IC IVAU,X6
	DSB ISH
	ISB
	BL f
	MOV W1,W10
	B Lout
f:
	B l0
l1:
	MOV W10,#2
	RET
l0:
	MOV W10,#1
	RET
Lout:
"""

[final]
expect = "sat"
assertion = "1:X0 = 1 & 1:X1 = 1"
